// Generated by Haxe 3.4.2
(function () { "use strict";
var Main = function() {
	var _gthis = this;
	var el = window.document.getElementById("myElement");
	var mc = new Hammer(el);
	mc.on("panleft panright tap press",function(ev) {
		el.textContent = ev.type + " gesture detected.";
	});
	var stage = window.document.getElementById("stage");
	var manager = new Hammer.Manager(stage);
	var pan = new Hammer.Pan();
	var rotate = new Hammer.Rotate();
	var pinch = new Hammer.Pinch();
	var tap = new Hammer.Tap({ taps : 1});
	var doubleTap = new Hammer.Tap({ event : "doubletap", taps : 2});
	rotate.recognizeWith([pan]);
	pinch.recognizeWith([rotate,pan]);
	doubleTap.recognizeWith([tap]);
	tap.requireFailure([doubleTap]);
	manager.add(pan);
	manager.add(rotate);
	manager.add(pinch);
	manager.add(doubleTap);
	manager.add(tap);
	var liveScale = 1;
	var currentRotation = 0;
	manager.on("rotatemove",function(e) {
		var rotation = currentRotation + Math.round(liveScale * e.rotation);
		stage.style.transform = "rotate(" + rotation + "deg)";
	});
	manager.on("rotateend",function(e1) {
		currentRotation += Math.round(e1.rotation);
	});
	var colors = [[20,187,95],[20,95,187],[187,95,20],[187,20,95],[95,20,187],[95,187,20]];
	var currentColorIndex = 0;
	manager.on("tap",function(e2) {
		currentColorIndex += 1;
		if(currentColorIndex >= colors.length) {
			currentColorIndex = 0;
		}
		stage.style.backgroundColor = _gthis.makeColor(colors[currentColorIndex]);
		stage.style.borderColor = _gthis.makeColor(colors[currentColorIndex],0.85);
	});
};
Main.main = function() {
	new Main();
};
Main.prototype = {
	mult: function(a,b) {
		return Math.round(a * b);
	}
	,makeColor: function(rgb,adj) {
		if(adj == null) {
			adj = 1;
		}
		return "rgb(" + this.mult(rgb[0],adj) + "," + this.mult(rgb[1],adj) + "," + this.mult(rgb[2],adj) + ")";
	}
};
Main.main();
})();

//# sourceMappingURL=hammer-demo.js.map